### PR TITLE
adding new Trusted App definitions from Community

### PR DESCRIPTION
**Pull request by ValentinIllich**
Hi all, finally I did add the mentioned trusted apps

### CODE REVIEW

**Comment by eblosug** [comment]
Thanks! But there is a small problem: the asterisk * does not work as expected in the domain list. But all sub-domains are whitelisted anyway, so please remove the wildcards in the domains of the WebEx list:

    *.ciscospark.com -> ciscopark.com
    etc.

**Comment by ValentinIllich** [comment]
OK no problem. Bur why do I need both of these then?

whatsapp.net
media-frx5-1.cdn.whatsapp.net

Without media... download of larger pictures will not work

**Comment by eblosug** [comment]
I tested what happens when I add these domains to a whitelist:

* whatsapp.net
* media-frx5-1.cdn.whatsapp.net

The second entry is not written to `/etc/squid/ssldomainwhitelist`, so it cannot have any effect.

Maybe something else happened during your test? Could you try to remove the CDN domain, force-quit the app and download a large file again?

By the way, I think all new entries should have

    "enabledPerDefault": false,

**Comment by ValentinIllich** [comment]
Now I have tried to reproduce the problem with WhatsApp. I did not succeed. So the addition of the detailed domains seems to be not necessary. I have removed them from the list.
I also agree with you that all new entries should not be enabled per default. I also changed this.

**Pull request merged**
